#!/bin/bash

#color codes
color_red='\e[0;31m'      #Red
color_green='\e[0;32m'    #Green
color_yellow='\e[0;33m'   #Yellow
color_blue='\e[0;34m'     #Blue
color_bred='\e[1;31m'     #Bold red
color_bgreen='\e[1;32m'   #Bold green
color_byellow='\e[1;33m'  #Bold yellow
color_bblue='\e[1;34m'    #Bold blue
color_reset='\e[0m'       #Reset color

#functions
lfs_me_help() {
    echo -e "${color_blue}LFS-ME ( Linux From Scratch made [more] easy ), a simple fakeroot based package manager for Linux from Scratch.\n"

    echo -e "${color_bblue}Usage:"
    echo -e "${color_blue}${0} ${color_bblue}mode [Options]${color_reset}\n"

    echo -e "${color_bblue}Modes:"
    echo -e "${color_bblue} build   ${color_blue}PKGBUILD-file    Build the package specified by PKGBUILD-file"
    echo -e "${color_bblue} install ${color_blue}package.pkg      Install the package package.pkg"
    echo -e "${color_bblue} remove  ${color_blue}package.pkg      Remove the package package.pkg, use this with care!"
    echo -e "${color_bblue} check   ${color_blue}package.pkg      Verify checksums of files installed by package.pkg\n"

    echo -e "${color_bblue}Options:"
    echo -e "${color_bblue} -b | --build-dir      ${color_blue}Specify the build directory"
    echo -e "${color_bblue} -D | --debug          ${color_blue}Enable debug mode"
    echo -e "${color_bblue} -f | --fakeroot_dir   ${color_blue}Specify the fakeroot directory"
    echo -e "${color_bblue} -h | --help           ${color_blue}Show this help"
    echo -e "${color_bblue}    | --no-checks      ${color_blue}Don't run checks"
    echo -e "${color_bblue}    | --no-color       ${color_blue}Disable color output"
    echo -e "${color_bblue} -p | --prefix         ${color_blue}Set install prefix"
    echo -e "${color_bblue} -s | --sources        ${color_blue}Set directory with source tarballs"
    echo -e "${color_reset}"


}

lfs_me_pause() {
    read -n1 -r -p "Press any key to continue..."
}

lfs_me_error() {
    echo -e "${color_bred}ERROR: ${1}${color_reset}" >&2
    lfs_me_help
    lfs_me_cleanup
    exit 1
}

lfs_me_message() {
    echo -e "${color_bgreen}${1}${color_reset}"
}

lfs_me_cleanup() {
    #clean up tempfiles
    if $debug; then lfs_me_pause; fi
    rm -rf "$temp_dir"
}

lfs_me_package() {
    #create metadata
    cd "$fakeroot_dir"
    find . -type l > "${fakeroot_dir}/LINKS"
    find . -type f > "${fakeroot_dir}/FILES"
    find . -type d > "${fakeroot_dir}/DIRS"
    find . -type f -exec md5sum {} \; | grep -ve "\\./md5sums$" > "${fakeroot_dir}/md5sums"
    #remove "." from the beginning of pathnames
    sed -i -e "s/^\\.//" "${fakeroot_dir}/FILES"
    sed -i -e "s/^\\.//" "${fakeroot_dir}/DIRS"
    sed -i -e "s/^\\.//" "${fakeroot_dir}/LINKS"

    #create package
    cd "$current_dir"
    cp "${temp_dir}/PKGBUILD" "${fakeroot_dir}/"
    if [[ ! -z ${pkgver_postfix} ]]; then
        fakeroot tar -cJf "${pkgname}-${pkgver}-${pkgver_postfix}.pkg" -C "$fakeroot_dir" .
    else
        fakeroot tar -cJf "${pkgname}-${pkgver}.pkg" -C "$fakeroot_dir" .
    fi

    #clean build directories
    rm -rf "${build_dir}/*" "${fakeroot_dir}/*"
}

#Those functions are allowed to be overwriten in PKGBUILD
lfs_me_prepare() {
    tar -xf "${sources_dir}/${pkgname}-${pkgver}.tar.bz2" -C "$build_dir"

    cd "${build_dir}/${pkgname}-${pkgver}"

    ./configure --prefix=/usr
}

lfs_me_build() {
    make
}

lfs_me_check() {
    make check 2>&1 | tee "${current_dir}/${pkgname}-check-log"
}

lfs_me_install() {
    make DESTDIR="${fakeroot_dir}" install
}

lfs_me_postinstall() {
    return
}

lfs_me_postremove() {
    return
}

#initialize variables
debug=false
temp_dir="$(mktemp -d)"
build_dir="${temp_dir}/build"
fakeroot_dir="${temp_dir}/fakeroot"
current_dir="$PWD"
run_checks=true
install_prefix=""
sources_dir="$current_dir"
mode="undefined"

#create build directory and fakeroot directory
mkdir -p "$build_dir" "$fakeroot_dir"

#Parse Arguments
while :
do
    case "$1" in
        -b | --build-dir)
            build_dir="$2"
            shift 2
            if [ ! -d "$build_dir" ]
            then
                lfs_me_error "Build directory \"${build_dir}\" not found!"
            fi
            ;;
        -D | --debug)
            debug=true
            shift
            ;;
        -f | --fakeroot-dir)
            fakeroot_dir="$2"
            shift 2
            if [ ! -d "$fakeroot_dir" ]
            then
                lfs_me_error "Fakeroot directory \"${build_dir}\" not found!"
            fi
            ;;
        -h | --help)
            lfs_me_help
            lfs_me_cleanup
            exit 0
            ;;
        --no-check)
            run_checks=false
            shift
            ;;
        --no-color)
            color_red=''
            color_green=''
            color_yellow=''
            color_blue=''
            color_bred=''
            color_bgreen=''
            color_byellow=''
            color_bblue=''
            color_reset=''
            shift
            ;;
        -p | --prefix)
            install_prefix="$2"
            shift 2
            if [ ! -d "$install_prefix" ]
            then
                lfs_me_error "Install prefix \"${install_prefix}\" not found!"
            fi
            ;;
        -s | --sources)
            sources_dir="$2"
            if [ ! -d "$sources_dir" ]
            then
                lfs_me_error "Sources dir \"${sources_dir}\" not found!"
            fi
            shift 2
            ;;
        build)
            if [ "$mode" != "undefined" ]
            then
                lfs_me_error "Only one action can be performed!"
            fi
            mode="build"
            pkgbuild_file="$2"
            if [ ! -f "$pkgbuild_file" ]
            then
                lfs_me_error "PKGBUILD file \"${pkgbuild_file}\" not found!"
            fi
            shift 2
            ;;
        install)
            if [ "$mode" != "undefined" ]
            then
                lfs_me_error "Only one action can be performed!"
            fi
            mode="install"
            package_file="$2"
            #check if valid tar archive and package file
            if ! tar -tf "$package_file" ./PKGBUILD ./FILES ./LINKS ./DIRS ./md5sums &> /dev/null
            then
                lfs_me_error "\"${package_file}\" is not a valid package file!"
            fi
            shift 2
            ;;
        remove)
            if [ "$mode" != "undefined" ]
            then
                lfs_me_error "Only one action can be performed!"
            fi
            mode="remove"
            package_file="$2"
            #check if valid tar archive and package file
            if ! tar -tf "$package_file" ./PKGBUILD ./FILES ./LINKS ./DIRS ./md5sums &> /dev/null
            then
                lfs_me_error "\"${package_file}\" is not a valid package file!"
            fi
            shift 2
            ;;
        check)
            if [ "$mode" != "undefined" ]
            then
                lfs_me_error "Only one action can be performed!"
            fi
            mode="check"
            package_file="$2"
            #check if valid tar archive and package file
            if ! tar -tf "$package_file" ./PKGBUILD ./FILES ./LINKS ./DIRS ./md5sums &> /dev/null
            then
                lfs_me_error "\"${package_file}\" is not a valid package file!"
            fi
            shift 2
            ;;
        -*)
            lfs_me_error "Unknown option \"$1\""
            ;;
        *)
            break
            ;;
    esac
done


case "$mode" in
    "build")
        cp "$pkgbuild_file" "${temp_dir}/PKGBUILD"
        source "${temp_dir}/PKGBUILD"
        
	    lfs_me_message "Preparing source"
        if $debug
        then
            lfs_me_pause
            #for some weird reason I can't use tee here to save the output
            lfs_me_prepare
        else
            lfs_me_prepare
        fi
        
	    lfs_me_message "Building"
        if $debug
        then 
            lfs_me_pause
            lfs_me_build 2>&1 | tee "${current_dir}/${pkgname}-build-log"
        else
            lfs_me_build
        fi
       
        if $run_checks
        then
            lfs_me_message "Running checks"
            if $debug; then lfs_me_pause; fi
            lfs_me_check
        fi
        
	    lfs_me_message "Installing to fakeroot"
        if $debug
        then 
            lfs_me_pause
            lfs_me_install 2>&1 | tee "${current_dir}/${pkgname}-install-log"

        else
            lfs_me_install
        fi
        
	    lfs_me_message "Packaging"
        if $debug; then lfs_me_pause; fi
        lfs_me_package
        ;;

    "install")
        #extract files
        lfs_me_message "Extracting package"
        if $debug; then lfs_me_pause; fi
        mkdir -pv "${fakeroot_dir}/${install_prefix}"
        tar -xJf "$package_file" -C "${fakeroot_dir}/${install_prefix}" --exclude ./PKGBUILD --exclude ./md5sums --exclude ./FILES --exclude ./DIRS --exclude ./LINKS
        tar -xJf "$package_file" -C ${temp_dir} ./PKGBUILD

        #install files with rsync
        lfs_me_message "Installing files"
        if $debug
        then 
            lfs_me_pause
            rsync -rlpgoDK "${fakeroot_dir}/" / 2>&1 | tee "${current_dir}/${pkgname}-install-log"
        else
            rsync -rlpgoDK "${fakeroot_dir}/" /
        fi

        #postinstall script
	    lfs_me_message "Running postinstall"
        cd "$temp_dir"
        source ./PKGBUILD
        if $debug
        then 
            lfs_me_pause
            lfs_me_postinstall 2>&1 | tee "${current_dir}/${pkgname}-postinstall-log"
        else
            lfs_me_postinstall
        fi
        ;;

    "remove")
        #extract meta files
        lfs_me_message "Extracting meta files"
        if $debug; then lfs_me_pause; fi
        tar -xJf "$package_file" -C "$temp_dir" ./FILES ./DIRS ./LINKS ./PKGBUILD

        #deleting files
        lfs_me_message "Deleting"
        if $debug; then lfs_me_pause; fi
	    cd "$temp_dir"
        #TODO: What about filenames with spaces and/or newline characters?
        rm -f $( cat FILES )
        #TODO: It might be possible to sort this so that there are only empty directories
        rmdir -p --ignore-fail-on-non-empty $( cat DIRS )
        for file in $( cat LINKS )
        do
            #only remove broken symlinks
            if ! test -r "$file"
            then
                rm -f "$file"
            fi
        done

        #postremove script
        lfs_me_message "Running postremove"
        source ./PKGBUILD
        if $debug
        then 
            lfs_me_pause
            lfs_me_postremove 2>&1 | tee "${current_dir}/${pkgname}-postremove-log"
        else
            lfs_me_postremove
        fi
        ;;
    "check")
	    #prepare md5sums
        lfs_me_message "Preparing md5sums"
        if $debug; then lfs_me_pause; fi
        tar -xJf "$package_file" -C "$temp_dir" ./md5sums
	    cd "$temp_dir"
	    grep -ve "[a-z0-9]\{32\}\\s*\\.\\/\(FILES$\|LINKS$\|DIRS$\)" md5sums > md5sums.grep
	    mv md5sums.grep md5sums

        #verify checksums
        lfs_me_message "Verifying checksums"
        cd /
        if $debug
        then 
            lfs_me_pause
            md5sum -c "$temp_dir/md5sums" 2>&1 | tee "${current_dir}/${pkgname}-check-log"
        else
            md5sum -c "$temp_dir/md5sums"
        fi
        ;;
    *)
        lfs_me_error "No action specified!"
        ;;
esac

lfs_me_cleanup
