#!/bin/bash

temp_dir=$(mktemp -d)
build_dir=${temp_dir}/build
fakeroot_dir=${temp_dir}/fakeroot
dir=$PWD

#create directories
mkdir -pv ${build_dir} ${fakeroot_dir}

#Setze spezielle Umgebungsvariablen, falls nicht vorhanden
if [[ ! -z ${LFS+x} ]]; then
    LFS=/mnt/lfs
fi
if [[ ! -z ${LFS_TGT+x} ]]; then
    LFS_TGT=$(uname -m)-lfs-linux-gnu
fi

pkg_package() {
    #Metadateien erzeugen
    cd ${fakeroot_dir}
    find . -type l > ${fakeroot_dir}/LINKS
    find . -type f > ${fakeroot_dir}/FILES
    find . -type d > ${fakeroot_dir}/DIRS
    find . -type f -exec md5sum {} \; | grep -ve "\\./md5sums$" > ${fakeroot_dir}/md5sums
    #"." vom Anfang der Dateipfade entfernen
    sed -i -e "s/^\\.//" ${fakeroot_dir}/FILES
    sed -i -e "s/^\\.//" ${fakeroot_dir}/DIRS
    sed -i -e "s/^\\.//" ${fakeroot_dir}/LINKS

    #Paket erzeugen
    cd $dir
    cp ${temp_dir}/PKGBUILD ${fakeroot_dir}/
    fakeroot tar -cJf ${pkgname}-${pkgver}.pkg -C ${fakeroot_dir} .

    #Verzeichnisse saeubern
    rm -rf ${build_dir}/* ${fakeroot_dir}/*
}

case $1 in
    "build")
        if [[ ! -z ${2+x} ]]; then
            cp $2 ${temp_dir}/PKGBUILD
	else
	    cp ./PKGBUILD ${temp_dir}/
        fi
        source ${temp_dir}/PKGBUILD
	echo Vorbereiten
        pkg_prepare
	echo Kompilieren
        pkg_build
	echo Ueberpruefen
        pkg_check
	echo Installieren
        pkg_install
	echo Packen
        pkg_package
        ;;
    "install")
        tar -xJf $2 -C / --exclude ./PKGBUILD --exclude ./md5sums --exclude ./FILES --exclude ./DIRS --exclude ./LINKS
        tar -xJf $2 -C ${temp_dir} ./PKGBUILD
        cd ${temp_dir}
        source ./PKGBUILD
	echo Postinstall
        pkg_postinstall
        ;;
    "remove")
        tar -xJf $2 -C ${temp_dir} ./FILES ./DIRS ./LINKS ./PKGBUILD
	cd ${temp_dir}
        rm -f $( cat FILES )
	rm -f $( cat LINKS )
        rmdir -p --ignore-fail-on-non-empty $( cat DIRS )
        source ./PKGBUILD
	echo Postremove-Skript
        pkg_remove
        rm ./FILES ./LINKS ./DIRS ./PKGBUILD
        ;;
    "check")
	echo Checksummen Pruefen
        tar -xJf $2 -C ${temp_dir} ./md5sums
	cd ${temp_dir}
	grep -ve "[a-z0-9]\{32\}\\s*\\.\\/\(FILES$\|LINKS$\|DIRS$\)" md5sums > md5sums.grep
	mv md5sums.grep md5sums
        cd /
        md5sum -c ${temp_dir}/md5sums
        ;;
    *)
        echo Einfacher Paketmanager
        echo Benutzung:
        echo -e \\t$0 build
        echo -e \\t$0 build PKGBUILD-datei
        echo -e \\t$0 install paket.pkg
        echo -e \\t$0 remove paket.pkg
        echo -e \\t$0 check paket.pkg
        ;;
esac

#cleanup
rm -rf ${temp_dir}

